[Greeter]
background=/etc/alternatives/desktop-login-background
content-align=center
theme-name=kOS-dark
icon-theme-name=Tela-circle-dracula-dark
cursor-theme-name=oreo_purple_cursors
cursor-theme-size=24
