# Dictionaries path
DictPath=
# Dictionary mode
DictMode="Built-in only"
# Enable suggestions
EnableSuggestions=True
# Show preedit text
ShowPreedit=True
# Ignored applications (comma-separated)
IgnoreApps=wrapper-2.0,thunar,terminal,private,keepass,seahorse,auth
# Toggle ignore current application
ToggleIgnoreKey=
# Toggle Ignore List
ToggleEnableKey=

[ToggleSuggestionsKey]
0=Shift+Scroll_Lock

