name: kazamOS Build

on:
  workflow_dispatch:
    inputs:
      wine:
        description: 'Install wine in the ISO'
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'

permissions:
  contents: write
  actions: write

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /opt/hostedtoolcache
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        sudo apt-get clean
        sudo docker image prune -af
        sudo df -h

    - name: Build ISO in Debian Trixie container
      run: |
        if [ "${{ inputs.wine }}" = "yes" ]; then
          sed -i "s/INSTALL_WINE/#/" build-output/kOS/terraform.conf
          echo "INSTALL_WINE=yes" >> build-output/kOS/terraform.conf
        fi
        mkdir -p build-output
        docker run --privileged --rm \
          -v $PWD/in:/in \
          -v $PWD/build-output:/output \
          debian:trixie \
          /in/kOS/build.sh

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: build-log
        path: build-output/build.log
        retention-days: 7

    - name: Upload rec
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: rec
        path: build-output/sizes_log*
        retention-days: 7

    - name: Cleanup build artifacts
      if: always()
      run: |
    
        echo "=== BEFORE CLEANUP ==="
        df -h .
        rm -rf binary live chroot cache boot
        rm -rf config
        echo "=== AFTER CLEANUP ==="
        df -h .

    - name: Verify ISO
      id: iso_name
      run: |
        . in/kOS/terraform.conf
        cd build-output

        for f in *.iso; do
          newname=$(echo $f | sed "s/live-image/kazamOS-$VERSION/")
          newname=$(echo $newname | sed "s/.hybrid//")
          mv $f $newname
        done

        ISO_FILE=$(ls *.iso 2>/dev/null | head -n 1 || echo "")
        if [ -n "$ISO_FILE" ]; then
          #mv $ISO_FILE "kazamOS.iso"
          #ISO_FILE="kazamOS.iso"
          if [ "$INSTALL_WINE" = "yes" ]; then
            mv "$ISO_FILE" "${ISO_FILE%.iso}.wine.iso"
            ISO_FILE="${ISO_FILE%.iso}.wine.iso"
          fi
          echo "filename=$ISO_FILE" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT

          echo "ISO_FILE=$ISO_FILE" >> $GITHUB_ENV
          
          # Additional ISO verification
          echo "ISO Details:"
          ls -lh "$ISO_FILE"
          file "$ISO_FILE"
          realpath "$ISO_FILE"
          
          # Check if ISO is bootable
          sudo apt install genisoimage -y
          if command -v isoinfo &> /dev/null; then
            echo "ISO Info:"
            isoinfo -d -i "$ISO_FILE" | grep -E "Volume|System|Boot"
          fi
        else
          echo "No ISO file found!"
          exit 1
        fi

    - name: Split ISO into parts
      run: |
        cd build-output
        ls -lah
    
        #ISO_FILE=$(ls *.iso 2>/dev/null | head -n 1 || echo "")
        if [ -z "$ISO_FILE" ]; then
          echo "No ISO file found to split!"
          exit 1
        fi
    
        echo "Splitting: $ISO_FILE"
        prefix="${ISO_FILE%.iso}-part."
        split --numeric-suffixes=1 --suffix-length=3 -b 800M "$ISO_FILE" "${prefix}"
    
        echo "Parts created:"
        ls -lh ${prefix}*
    
        sha256sum "$ISO_FILE"
        sha256sum ${prefix}*

    - name: Setup rsync
      run: |
        sudo apt update
        sudo apt install rsync openssh-client -y
        mkdir -p ~/.ssh
        echo "${{ secrets.SF_SSH_KEY }}" > ~/.ssh/sf_key
        chmod 600 ~/.ssh/sf_key
        ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
        cat ~/.ssh/sf_key | head -1
        cat ~/.ssh/sf_key | tail -1

    - name: Upload ISO to sourceforg via rsync
      env:
        SF_USER: kazam0180
        SF_PROJECT: kazamos
      run: |
        cd build-output
        ls -lah
        md5sum "${ISO_FILE%.iso}"* | tee kazamOS_md5sum.txt
        timestamp=$(date +%H.%M_%d-%B-%Y-%Z)
        # copy the iso to remote
        for f in "${ISO_FILE%.iso}"*; do
          [ -e "$f" ] || continue
          exit
          rsync -avP \
            -e "ssh -v -i ~/.ssh/sf_key -o StrictHostKeyChecking=no -o IdentitiesOnly=yes" \
            "$f" \
            ${SF_USER}@frs.sourceforge.net:/home/frs/project/${SF_PROJECT}/$timestamp/
        done

    - name: Setup rclone
      uses: AnimMouse/setup-rclone@v1

    - name: Upload ISO to pcloud via rclone
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_REMOTE: "my_pcloud:kazamOS"
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONF" | base64 -d > ~/.config/rclone/rclone.conf
        cd build-output
        # copy the iso to remote
        for f in *.iso; do
          [ -e "$f" ] || continue
          rclone copy --progress "$f" "$RCLONE_REMOTE/"
        done
        ls -lh

    - name: Create Release
      run: |
        cd build-output
        RELEASE_TAG="cooking-$(date +'%H%M_%d.%m.%Y')"
        gh release create "$RELEASE_TAG" \
          ./kazamOS-2.0-amd64-part* \
          --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
